# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iCambio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iCambio
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'CodableFirebase'
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'

end
